docno="lists-014-11306635"
received="Thu Feb 26 11:16:30 2004"
isoreceived="20040226161630"
sent="Thu, 26 Feb 2004 16:16:28 +0000"
isosent="20040226161628"
name="Sean B. Palmer"
email="sean@mysterylights.com"
subject="BUG: Recursion Error With &#64;keywords this"
id="403E1BDC.50105@mysterylights.com"
charset="usascii"
expires="1"


To:public-cwm-bugs@w3.org


$ echo '@keywords this . @prefix : <#> . this :a :Doc .' | cwm

[...]
   File "/misc/tools/cwm/pretty.py", line 312, in _scan
     self._scan(y, x)
   File "/misc/tools/cwm/pretty.py", line 312, in _scan
     self._scan(y, x)
   File "/misc/tools/cwm/pretty.py", line 293, in _scan
     if verbosity() > 98: progress("scanning %s in context %s"
        %(`x`, `context`),
RuntimeError: maximum recursion depth exceeded

The problem occurs in a CVS version checked out today, as well as the 
most recent cwm.tgz.

-- 
Sean B. Palmer, <http://purl.org/net/sbp/>
"phenomicity by the bucketful" - http://miscoranda.com/



