docno="lists-097-9661475"
received="Fri Dec  7 17:30:22 2001"
isoreceived="20011207223022"
sent="Fri, 07 Dec 2001 16:30:20 -0600"
isosent="20011207223020"
name="Dan Connolly"
email="connolly@w3.org"
subject="llyn RuntimeError: Already in store but bindings new?"
id="3C1142FC.5F5C6281@w3.org"
charset="us-ascii"
expires="-1"


To:timbl@w3.org, www-archive+n3bugs@w3.org

I'm trying to make a picture of bwm's RDF schema for P3P,
but cwm craps out thusly:

$ python cwm.py --chatty=20 --rdf
http://lists.w3.org/Archives/Public/www-archive/2001Dec/att-0006/02-p3p-rdf-schema.xml
--n3 http://www.w3.org/2001/02pd/rdf-schema-fig.n3 --think
--base=ephemeral: --bySubject --rdf=c > p3pFig.rdf

[...]
        *** Conclude: _formula  ::  theGraph   hasNode  Resource  .
        *** Conclude: _formula  ::  theGraph   hasNode  PolicyRefs  .
        *** Conclude: _formula  ::  theGraph   hasNode       Seq  .
Concluding: Forget it, already had ???@@@@?? c->PolicyRefs
c2->PolicyResource
Already list:  [[(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c>,
<http://www.w3.org/2001/09/P3Pv1#PolicyResource>),
(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c2>,
<http://www.w3.org/2000/01/rdf-schema#Resource>)],
[(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c>,
<http://www.w3.org/2001/09/P3Pv1#PolicyRefs>),
(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c2>,
<http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq>)],
[(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c>,
<http://www.w3.org/2001/09/P3Pv1#PolicyRefs>),
(<http://www.w3.org/2001/02pd/rdf-schema-fig.n3#c2>,
<http://www.w3.org/2001/09/P3Pv1#PolicyResource>)]]
Traceback (most recent call last):
  File "cwm.py", line 598, in ?
    doCommand()
  File "cwm.py", line 551, in doCommand
    _store.think(workingContext)
  File "../../../2000/10/swap/llyn.py", line 1372, in think
    step = self.applyRules(F, F, alreadyDictionary=bindingsFound)
  File "../../../2000/10/swap/llyn.py", line 1423, in applyRules
    already=already)
  File "../../../2000/10/swap/llyn.py", line 1478, in tryRule
    self.conclude, ( self, conclusions, targetContext, _outputVariables,
already))
  File "../../../2000/10/swap/llyn.py", line 1796, in match
    bindings=[], justOne=justOne)
  File "../../../2000/10/swap/llyn.py", line 2017, in query
    bindings[:], nb[:], justOne=justOne)
  File "../../../2000/10/swap/llyn.py", line 1890, in query
    return action(bindings, param)  # No terms left .. success!
  File "../../../2000/10/swap/llyn.py", line 2164, in conclude
    if already != None: raise RuntimeError, "Already in store but
bindings new?"RuntimeError: Already in store but bindings new?

$ ident llyn.py cwm.py notation3.py
llyn.py:
     $Id: llyn.py,v 1.6 2001/12/04 20:28:22 timbl Exp $

cwm.py:
     $Id: cwm.py,v 1.82 2001/11/15 22:11:23 timbl Exp $
     $Id: cwm.py,v 1.82 2001/11/15 22:11:23 timbl Exp $

notation3.py:
     $Id: notation3.py,v 1.98 2001/11/15 22:11:24 timbl Exp $
     $Id: notation3.py,v 1.98 2001/11/15 22:11:24 timbl Exp $

-- 
Dan Connolly, W3C http://www.w3.org/People/Connolly/



